[tool.towncrier]
package = "opendebates"
package_dir = "opendebates"
directory = "changes"
filename = "CHANGELOG.rst"
issue_format = "`#{issue} <https://github.com/OpenDebates/OpenDebates/issues/{issue}>`_"
type = [
    { name = "Breaking Changes",            directory = "breaking",     showcontent = true },
    { name = "Deprecation",                 directory = "deprecation",  showcontent = true },
    { name = "Features",                    directory = "feature",      showcontent = true },
    { name = "Bugfixes",                    directory = "bugfix",       showcontent = true },
    { name = "Documentation Improvements",  directory = "doc",          showcontent = true },
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --strict-markers --ignore=docs/conf.py --ignore=setup.py --ignore=.eggs --doctest-modules --doctest-glob=/*.rst --tb=short"
norecursedirs = [
	".git",
	".tox",
	".env",
	"dist",
	"build",
	"migrations"
]
testpaths = [
    "tests"
]
python_files = [
	"test_*.py",
	"*_test.py",
	"tests.py"
]

[tool.poetry]
name = "OpenDebates"
version = "0.1.0"
description = "Open Source Semantic Wiki and Debate Platform"
authors = ["Taven <taven@opendebates.net>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/OpenDebates/OpenDebates"
repository = "https://github.com/OpenDebates/OpenDebates"
documentation = "https://opendebates.readthedocs.io"
keywords = [
    "debate",
    "wiki",
    "semantic",
    "linguistics"
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.11",
]
packages = [
    { include = "opengrammar" }
]
include = [
    ".bumpversion.cfg",
    ".coveragerc",
    ".editorconfig",
    ".readthedocs.yml",
    "AUTHORS.rst",
    "tests/*",
    "poetry.lock",
    "pyproject.toml"
]

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
lark = "^1.1.5"
aiohttp = "^3.8.3"
fastapi = "^0.89.1"
toml = "^0.10.2"
schema = "^0.7.5"
sentry-sdk = "^1.14.0"
loguru = "^0.6.0"
beanie = "^1.17.0"


[tool.poetry.group.tests.dependencies]
pytest = "^7.2.0"
pytest-cov = "^4.0.0"

[tool.poetry.group.release.dependencies]
isort = "^5.12.0"
twine = "^4.0.1"
codecov = "^2.1.12"
bump2version = "^1.0.1"
black = "^23.1.0"
towncrier = "^22.8.0"
build = "^0.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"