name: Tests
on: [push, pull_request]
jobs:
  tests:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu, MacOS, Windows]
        python-version: ["3.11"]
        experimental: [false]
    defaults:
      run:
        shell: bash
    steps:
        - uses: actions/checkout@v3
        - name: Install Poetry
          run: pipx install poetry
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
            cache: 'poetry'
        - name: Set ENV
          run: |
              echo "MKL_CBWR=AUTO" >> $GITHUB_ENV
              echo "PYTHONHASHSEED=0" >> $GITHUB_ENV
        - name: Run Tests
          run: |
              python -m pip install --upgrade pip build
              poetry install --with tests,release
              python -m build
              twine check dist/*
              pytest . --cov --cov-report=term-missing -vv --doctest-glob="*.py"
              coverage report
              coverage html
              coverage xml --ignore-errors
          continue-on-error: ${{ matrix.experimental }}
        - name: "Upload coverage to Codecov"
          uses: codecov/codecov-action@v3
          with:
            fail_ci_if_error: ${{ !matrix.experimental }}
